import MainLayout from '@Layouts/MainLayout';
import '@Styles/app.scss';
import type { Metadata } from 'next';
import { DM_Sans, Montserrat } from 'next/font/google';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Nimbus Air',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactNode {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${montserrat.variable}`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
